python main.py -t 1.9 -s opt_tool_test/19.pkl -p opt_tool_test/18.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.0 -s opt_tool_test/20.pkl -p opt_tool_test/19.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.1 -s opt_tool_test/21.pkl -p opt_tool_test/20.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.2 -s opt_tool_test/22.pkl -p opt_tool_test/21.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.3 -s opt_tool_test/23.pkl -p opt_tool_test/22.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.4 -s opt_tool_test/24.pkl -p opt_tool_test/23.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.5 -s opt_tool_test/25.pkl -p opt_tool_test/24.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.6 -s opt_tool_test/26.pkl -p opt_tool_test/25.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.7 -s opt_tool_test/27.pkl -p opt_tool_test/26.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.8 -s opt_tool_test/28.pkl -p opt_tool_test/27.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 2.9 -s opt_tool_test/29.pkl -p opt_tool_test/28.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 3.0 -s opt_tool_test/30.pkl -p opt_tool_test/29.pkl --basis 3 --reach 2 --push 2 --tool 4
python main.py -t 3.1 -s opt_tool_test/31.pkl -p opt_tool_test/30.pkl --basis 3 --reach 2 --push 2 --tool 4
